# NAME:		Zhenghao Li
# EMAIL:	lizhenghao99@g.ucla.edu
# ID:		704971934

default: dist

dist: my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
	tar -czf lab4a-704971934.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

clean:
	rm -f lab4a-704971934.tar.gz